const ff = [
  { downloadTitle: "floral-finance-july-2022" },
  { downloadTitle: "floral-finance-june-2022" },
  { downloadTitle: "floral-finance-may-2022" },
  { downloadTitle: "floral-finance-april-2022" },
  { downloadTitle: "floral-finance-march-2022" },
  { downloadTitle: "floral-finance-february-2022" },
  { downloadTitle: "floral-finance-january-2022" },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];

const articles = [
  {
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "From the Publishers: Looking Back ... Looking Ahead",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "Cash Flow: Now Is the Time to Plan",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 4,
    name: "Cash Flow Forecasting: Knowledge Is Power",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 6,
    name: "Cut Your Payroll: Key to Seasoned Success",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 7,
    name: "By the Books: Non-Holiday Staffing Analysis—Know What You Can Afford",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: Entertaining Children",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: August Cash",
  },
  { fileCore: "floral-finance-july-2022", page: 8, name: "Norms: Shrink" },

  {
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "From the Publishers: The Ethics of Payables",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "making money in the slow months: can it be done?",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 4,
    name: "your business plan: the how & the why",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 6,
    name: "the family business: perks—getting something for nothing",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 7,
    name: "by the books: smart buying—a key to profitability",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "inquiries & answers: paid holidays for employees",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "inquiries & answers: teaching old dogs",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "norms: sales from floral",
  },

  {
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "from the publishers: effective collections",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "thinking on the margin: a lesson from hockey",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 4,
    name: "$776,487 in sales: $2,830 in profit",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 6,
    name: "the family business: family relationships",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 7,
    name: "by the books: your advertising budget—allocating advertising dollars",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "inquiries & answers: low-cost mortgages",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "inquiries & answers: liability protection",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "norms: average discounts",
  },

  {
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "from the publishers: collecting accounts",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "do retail florists make money?: a path to profits",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 4,
    name: "you & your corporation: how's the relationship going?",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 6,
    name: "money smarts: savings strategies",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 7,
    name: "by the books: gift card accounting: do it right",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "inquiries & answers: order accuracy",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "inquiries & answers: training new-hires",
  },
  { fileCore: "floral-finance-april-2022", page: 8, name: "norms: lost sales" },

  {
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "from the publishers: success",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "house accounts: part 2: the mechanics matter",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 4,
    name: "evaluating advertising: making your investment pay",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 6,
    name: "by the books: traditional wedding protocol: a checklist for guidance",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "inquiries & answers: shoplifting",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "inquiries & answers: part-time space",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "norms: advertising spend",
  },

  {
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "from the publishers: inertia",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "house accounts: part 1: when should you extend credit?",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 4,
    name: "shop profile: making money in february: one florist’s story",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 6,
    name: "finding the help you need: the challenge—the solution",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 7,
    name: "by the books: punching in early … staying late",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "inquiries & answers: loss leaders",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "inquiries & answers: coupon power",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "norms: other expenses",
  },

  {
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "from the publishers: delegation",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "your business review: there’s no better time",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 4,
    name: "owning your building: is it practical?",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 6,
    name: "credit card perks: free airline travel",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 7,
    name: "by the books: tips on managing holiday volume: short on space?",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "inquiries & answers: cash flow",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "inquiries & answers: giving away that old car",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "norms: monthly sales",
  },

  {
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "from the publishers: learning through life",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "financial checklists: take care of those you care for",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 4,
    name: "gift cards, gift certificates: real moneymakers",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 6,
    name: "guarding your profits: opportunities or threats?",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 7,
    name: "by the books: atm tips",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "inquiries & answers: managing partnerships",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "inquiries & answers: speaking of partnerships",
  },
  { fileCore: "floral-finance-december-2021", page: 8, name: "norms: over 60" },

  {
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "from the publishers: thoughts of success",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "it's payday! is everyone happy?",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 4,
    name: "'special' sales: are they even necessary?'",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 6,
    name: "capitalism: the many gifts of business",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 7,
    name: "by the books: wires-out service charges",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "inquiries & answers: inventory turns",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "inquiries & answers: pricing multiple deliveries",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "norms: gift sales",
  },

  {
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "from the publishers: getting people to listen",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "giving away the store: how to account for it",
  },
  { fileCore: "floral-finance-october-2021",
    page: 4, name: "managing the holidays: take time to get ready" },
  {
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "opportunities of a certain age: for your top & bottom lines",
  },
  { date: "1021.7", name: "by the books: pricing expensive flowers" },
  { date: "1021.8", name: "inquiries & answers: used computers" },
  { date: "1021.8", name: "inquiries & answers: internet advertising" },
  { date: "1021.8", name: "norms: amazon sales" },

  { date: "0921.2", name: "from the publishers: are there benefits to anger?" },
  {
    date: "0921.2",
    name: "selling by the stem: join the bandwagon",
  },
  {
    date: "0921.4",
    name: "one customer, two sales: an easier way to increase volume",
  },
  {
    date: "0921.6",
    name: "paying for layoffs",
  },
  {
    date: "0921.7",
    name: "by the books: help your accountant: you're not a retailer",
  },
  { date: "0921.8", name: "inquiries & answers: honoring expired coupons" },
  { date: "0921.8", name: "inquiries & answers: inventorying fresh flowers" },
  { date: "0921.8", name: "norms: fresh flowers & greens" },

  { date: "0821.2", name: "from the publishers: relationships" },
  {
    date: "0821.2",
    name: "is contract labor a good idea? how do i know if it's legal to hire contract drivers?",
  },
  {
    date: "0821.4",
    name: "facing a financial crisis",
  },
  {
    date: "0821.6",
    name: "employee discounts: a low-cost benefit your employees will love",
  },
  {
    date: "0821.7",
    name: "by the books: the numbers on contract labor",
  },
  { date: "0821.8", name: "inquiries & answers: too much rent" },
  {
    date: "0821.8",
    name: "inquiries & answers: ringing up incoming wire orders",
  },
  { date: "0821.8", name: "norms: sales increase" },
];
