const ff = [
  { downloadTitle: "floral-finance-july-2022" },
  { downloadTitle: "floral-finance-june-2022" },
  { downloadTitle: "floral-finance-may-2022" },
  { downloadTitle: "floral-finance-april-2022" },
  { downloadTitle: "floral-finance-march-2022" },
  { downloadTitle: "floral-finance-february-2022" },
  { downloadTitle: "floral-finance-january-2022" },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];

const articles = [
  {
    date: "0722.2",
    name: "from the publishers: looking back ... looking ahead",
  },
  { date: "0722.2", name: "cash flow: now is the time to plan" },
  { date: "0722.4", name: "cash flow forecasting: knowledge is power" },
  { date: "0722.6", name: "cut your payroll: key to seasoned success" },
  {
    date: "0722.7",
    name: "by the books: non-holiday staffing analysis—know what you can afford",
  },
  { date: "0722.8", name: "inquiries & answers: entertaining children" },
  { date: "0722.8", name: "inquiries & answers: august cash" },
  { date: "0722.8", name: "norms: shrink" },

  { date: "0622.2", name: "from the publishers: the ethics of payables" },
  { date: "0622.2", name: "making money in the slow months: can it be done?" },
  { date: "0622.4", name: "your business plan: the how & the why" },
  {
    date: "0622.6",
    name: "the family business: perks—getting something for nothing",
  },
  { date: "0622.7", name: "by the books: smart buying—a key to profitability" },
  { date: "0622.8", name: "inquiries & answers: paid holidays for employees" },
  { date: "0622.8", name: "inquiries & answers: teaching old dogs" },
  { date: "0622.8", name: "norms: sales from floral" },

  { date: "0522.2", name: "from the publishers: effective collections" },
  { date: "0522.2", name: "thinking on the margin: a lesson from hockey" },
  { date: "0522.4", name: "$776,487 in sales: $2,830 in profit" },
  { date: "0522.6", name: "the family business: family relationships" },
  {
    date: "0522.7",
    name: "by the books: your advertising budget—allocating advertising dollars",
  },
  { date: "0522.8", name: "inquiries & answers: low-cost mortgages" },
  { date: "0522.8", name: "inquiries & answers: liability protection" },
  { date: "0522.8", name: "norms: average discounts" },

  { date: "0422.2", name: "from the publishers: collecting accounts" },
  { date: "0422.2", name: "do retail florists make money?: a path to profits" },
  {
    date: "0422.4",
    name: "you & your corporation: how's the relationship going?",
  },
  { date: "0422.6", name: "money smarts: savings strategies" },
  { date: "0422.7", name: "by the books: gift card accounting: do it right" },
  { date: "0422.8", name: "inquiries & answers: order accuracy" },
  { date: "0422.8", name: "inquiries & answers: training new-hires" },
  { date: "0422.8", name: "norms: lost sales" },

  { date: "0322.2", name: "from the publishers: success" },
  { date: "0322.2", name: "house accounts: part 2: the mechanics matter" },
  {
    date: "0322.4",
    name: "evaluating advertising: making your investment pay",
  },
  {
    date: "0322.6",
    name: "by the books: traditional wedding protocol: a checklist for guidance",
  },
  { date: "0322.8", name: "inquiries & answers: shoplifting" },
  { date: "0322.8", name: "inquiries & answers: part-time space" },
  { date: "0322.8", name: "norms: advertising spend" },

  { date: "0222.2", name: "from the publishers: inertia" },
  {
    date: "0222.2",
    name: "house accounts: part 1: when should you extend credit?",
  },
  {
    date: "0222.4",
    name: "shop profile: making money in february: one florist’s story",
  },
  {
    date: "0222.6",
    name: "finding the help you need: the challenge—the solution",
  },
  { date: "0222.7", name: "by the books: punching in early … staying late" },
  { date: "0222.8", name: "inquiries & answers: loss leaders" },
  { date: "0222.8", name: "inquiries & answers: coupon power" },
  { date: "0222.8", name: "norms: other expenses" },

  { date: "0122.2", name: "from the publishers: delegation" },
  { date: "0122.2", name: "your business review: there’s no better time" },
  { date: "0122.4", name: "owning your building: is it practical?" },
  { date: "0122.6", name: "credit card perks: free airline travel" },
  {
    date: "0122.7",
    name: "by the books: tips on managing holiday volume: short on space?",
  },
  { date: "0122.8", name: "inquiries & answers: cash flow" },
  { date: "0122.8", name: "inquiries & answers: giving away that old car" },
  { date: "0122.8", name: "norms: monthly sales" },

  { date: "1221.2", name: "from the publishers: learning through life" },
  {
    date: "1221.2",
    name: "financial checklists: take care of those you care for",
  },
  { date: "1221.4", name: "gift cards, gift certificates: real moneymakers" },
  { date: "1221.6", name: "guarding your profits: opportunities or threats?" },
  { date: "1221.7", name: "by the books: atm tips" },
  { date: "1221.8", name: "inquiries & answers: managing partnerships" },
  { date: "1221.8", name: "inquiries & answers: speaking of partnerships" },
  { date: "1221.8", name: "norms: over 60" },

  { date: "1121.2", name: "from the publishers: thoughts of success" },
  {
    date: "1121.2",
    name: "it's payday! is everyone happy?",
  },
  { date: "1121.4", name: "'special' sales: are they even necessary?'" },
  { date: "1121.6", name: "capitalism: the many gifts of business" },
  { date: "1121.7", name: "by the books: wires-out service charges" },
  { date: "1121.8", name: "inquiries & answers: inventory turns;" },
  { date: "1121.8", name: "inquiries & answers: pricing multiple deliveries" },
  { date: "1121.8", name: "norms: gift sales" },

  { date: "1021.2", name: "from the publishers: getting people to listen" },
  {
    date: "1021.2",
    name: "giving away the store: how to account for it",
  },
  { date: "1021.4", name: "managing the holidays: take time to get ready" },
  {
    date: "1021.6",
    name: "OPPORTUNITIES OF A CERTAIN AGE: For Your Top & Bottom Lines",
  },
  { date: "1021.7", name: "by the books: wires-out service charges" },
  { date: "1021.8", name: "inquiries & answers: inventory turns;" },
  { date: "1021.8", name: "inquiries & answers: pricing multiple deliveries" },
  { date: "1021.8", name: "norms: gift sales" },
];
