const ff = [
  {
    downloadTitle: "floral-finance-july-2022",
    line2: [
      "from the publishers: looking back ... looking ahead",
      "cash flow: now is the time to plan",
    ],
    line4: "cash flow forecasting: knowledge is power",
    line6: "cut your payroll: key to seasoned success",
    line7: "by the books: non-holiday staffing analysis—know what you can afford",
    line8: [
      "inquiries & answers: entertaining children; august cash",
      "norms: shrink",
    ],
  },
  {
    downloadTitle: "floral-finance-june-2022",
    line2: [
      "from the publishers: the ethics of payables",
      "making money in the slow months: can it be done?",
    ],
    line4: "your business plan: the how & the why",
    line6: "the family business: perks—getting something for nothing",
    line7: "by the books: smart buying—a key to profitability",
    line8: [
      "inquiries & answers: paid holidays for employees; teaching old dogs",
      "norms: sales from floral",
    ],
  },
  {
    downloadTitle: "floral-finance-may-2022",
    line2: [
      "from the publishers: effective collections",
      "thinking on the margin: a lesson from hockey",
    ],
    line4: "$776,487 in sales: $2,830 in profit",
    line6: "the family business: family relationships",
    line7: "by the books: your advertising budget—allocating advertising dollars",
    line8: [
      "inquiries & answers: low-cost mortgages; liability protection",
      "norms: average discounts",
    ],
  },
  {
    downloadTitle: "floral-finance-april-2022",
    line2: [
      "from the publishers: collecting accounts",
      "do retail florists make money?: a path to profits",
    ],
    line4: "you & your corporation: how's the relationship going?",
    line6: "money smarts: savings strategies",
    line7: "by the books: gift card accounting: do it right",
    line8: [
      "inquiries & answers: order accuracy; training new-hires",
      "norms: lost sales",
    ],
  },
  {
    downloadTitle: "floral-finance-march-2022",
    line2: [
      "from the publishers: success",
      "house accounts: part 2: the mechanics matter",
    ],
    line4: "evaluating advertising: making your investment pay",
    line6: "by the books: traditional wedding protocol: a checklist for guidance",
    line8: [
      "inquiries & answers: shoplifting; part-time space",
      "norms: advertising spend",
    ],
  },
  {
    downloadTitle: "floral-finance-february-2022",
    line2: [
      "from the publishers: inertia",
      "house accounts: part 1: when should you extend credit?",
    ],
    line4: "shop profile: making money in february: one florist’s story",
    line6: "finding the help you need: the challenge—the solution",
    line7: "by the books: punching in early … staying late",
    line8: [
      "inquiries & answers: loss leaders; coupon power",
      "norms: other expenses",
    ],
  },
  {
    downloadTitle: "floral-finance-january-2022",
    line2: [
      "from the publishers: delegation",
      "your business review: there’s no better time",
    ],
    line4: "owning your building: is it practical?",
    line: "credit card perks: free airline travel",
    line7: "by the books: tips on managing holiday volume: short on space?",
    line8: [
      "inquiries & answers: cash flow; giving away that old car",
      "norms: monthly sales",
    ],
  },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
//   { downloadTitle: "floral-finance-february-2020" },
//   { downloadTitle: "floral-finance-january-2020" },
//   { downloadTitle: "floral-finance-december-2019" },
//   { downloadTitle: "floral-finance-november-2019" },
//   { downloadTitle: "floral-finance-october-2019" },
//   { downloadTitle: "floral-finance-september-2019" },
//   { downloadTitle: "floral-finance-august-2019" },
//   { downloadTitle: "floral-finance-july-2019" },
//   { downloadTitle: "floral-finance-june-2019" },
//   { downloadTitle: "floral-finance-may-2019" },
//   { downloadTitle: "floral-finance-april-2019" },
//   { downloadTitle: "floral-finance-march-2019" },
//   { downloadTitle: "floral-finance-february-2019" },
//   { downloadTitle: "floral-finance-january-2019" },
//   { downloadTitle: "floral-finance-december-2018" },
//   { downloadTitle: "floral-finance-november-2018" },
//   { downloadTitle: "floral-finance-october-2018" },
//   { downloadTitle: "floral-finance-september-2018" },
//   { downloadTitle: "floral-finance-august-2018" },
//   { downloadTitle: "floral-finance-july-2018" },
//   { downloadTitle: "floral-finance-june-2018" },
//   { downloadTitle: "floral-finance-may-2018" },
//   { downloadTitle: "floral-finance-april-2018" },
//   { downloadTitle: "floral-finance-march-2018" },
//   { downloadTitle: "floral-finance-february-2018" },
//   { downloadTitle: "floral-finance-january-2018" },
//   { downloadTitle: "floral-finance-december-2017" },
//   { downloadTitle: "floral-finance-november-2017" },
//   { downloadTitle: "floral-finance-october-2017" },
//   { downloadTitle: "floral-finance-september-2017" },
//   { downloadTitle: "floral-finance-august-2017" },
//   { downloadTitle: "floral-finance-july-2017" },
//   { downloadTitle: "floral-finance-june-2017" },
//   { downloadTitle: "floral-finance-may-2017" },
//   { downloadTitle: "floral-finance-april-2017" },
//   { downloadTitle: "floral-finance-march-2017" },
//   { downloadTitle: "floral-finance-february-2017" },
//   { downloadTitle: "floral-finance-january-2017" },
//   { downloadTitle: "floral-finance-december-2016" },
//   { downloadTitle: "floral-finance-november-2016" },
//   { downloadTitle: "floral-finance-october-2016" },
//   { downloadTitle: "floral-finance-september-2016" },
//   { downloadTitle: "floral-finance-august-2016" },
//   { downloadTitle: "floral-finance-july-2016" },
//   { downloadTitle: "floral-finance-june-2016" },
//   { downloadTitle: "floral-finance-may-2016" },
//   { downloadTitle: "floral-finance-april-2016" },
//   { downloadTitle: "floral-finance-march-2016" },
//   { downloadTitle: "floral-finance-february-2016" },
//   { downloadTitle: "floral-finance-january-2016" },
//   { downloadTitle: "floral-finance-december-2015" },
//   { downloadTitle: "floral-finance-november-2015" },
//   { downloadTitle: "floral-finance-october-2015" },
//   { downloadTitle: "floral-finance-september-2015" },
];
