const ff = [
  {
    downloadTitle: "floral-finance-may-2022",
    "2a": "from the publishers: effective collections",
    "2b": "thinking on the margin: a lesson from hockey",
    "4a": "$776,487 in sales: $2,830 in profit",
    "6a": "the family business: family relationships",
    "7a": "by the books: your advertising budget—allocating advertising dollars",
    "8a": "inquiries & answers: low-cost mortgages; liability protection",
    "8b": "norms: average discounts",
  },
  {
    downloadTitle: "floral-finance-april-2022",
    "2a": "from the publishers: collecting accounts",
    "2b": "do retail florists make money?: a path to profits",
    "4a": "you & your corporation: how's the relationship going?",
    "6a": "money smarts: savings strategies",
    "7a": "by the books: gift card accounting: do it right",
    "8a": "inquiries & answers: order accuracy; training new-hires",
    "8b": "norms: lost sales",
  },
 {
    downloadTitle: "floral-finance-march-2022",
    "2a": "from the publishers: success",
    "2b": "house accounts: part 2: the mechanics matter",
    "4a": "evaluating advertising: making your investment pay",
    "6a": "by the books: traditional wedding protocol: a checklist for guidance",
    "8a": "inquiries & answers: shoplifting; part-time space",
    "8a": "norms: advertising spend",
  },
  {
    downloadTitle: "floral-finance-february-2022",
    "2a": "from the publishers: inertia",
    "2b": "house accounts: part 1: when should you extend credit?",
    "4": "shop profile: making money in february: one florist’s story",
    "6": "finding the help you need: the challenge—the solution",
    "7": "by the books: punching in early … staying late",
    "8": "inquiries & answers: loss leaders; coupon power",
    "8": "norms: other expenses",
  },
  {
    downloadTitle: "floral-finance-january-2022",
    "2": "from the publishers: delegation",
    "2": "your business review: there’s no better time",
    "4": "owning your building: is it practical?",
    "6": "credit card perks: free airline travel",
    "7": "by the books: tips on managing holiday volume: short on space?",
    "8": "inquiries & answers: cash flow; giving away that old car",
    "8": "norms: monthly sales",
  },


  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];
