const ff = [
  { downloadTitle: "floral-finance-july-2022" },
  { downloadTitle: "floral-finance-june-2022" },
  { downloadTitle: "floral-finance-may-2022" },
  { downloadTitle: "floral-finance-april-2022" },
  { downloadTitle: "floral-finance-march-2022" },
  { downloadTitle: "floral-finance-february-2022" },
  { downloadTitle: "floral-finance-january-2022" },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];

const articles = [
  {
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "From the Publishers: Looking Back ... Looking Ahead",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "Cash Flow: Now Is the Time to Plan",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 4,
    name: "Cash Flow Forecasting: Knowledge Is Power",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 6,
    name: "Cut Your Payroll: Key to Seasoned Success",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 7,
    name: "By the Books: Non-Holiday Staffing Analysis—Know What You Can Afford",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: Entertaining Children",
  },
  {
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: August Cash",
  },
  { fileCore: "floral-finance-july-2022", page: 8, name: "Norms: Shrink" },

  {
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "From the Publishers: The Ethics of Payables",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "Making Money in the Slow Months: Can It Be Done?",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 4,
    name: "Your Business Plan: The How & the Why",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 6,
    name: "The Family Business: Perks—Getting Something for Nothing",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 7,
    name: "By the Books: Smart Buying—a Key to Profitability",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Inquiries & Answers: Paid Holidays for Employees",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Inquiries & Answers: Teaching Old Dogs",
  },
  {
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Norms: Sales From Floral",
  },

  {
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "From the Publishers: Effective Collections",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "Thinking on the Margin: A Lesson From Hockey",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 4,
    name: "$776,487 in Sales: $2,830 in Profit",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 6,
    name: "The Family Business: Family Relationships",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 7,
    name: "By the Books: Your Advertising Budget—Allocating Advertising Dollars",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Inquiries & Answers: Low-Cost Mortgages",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Inquiries & Answers: Liability Protection",
  },
  {
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Norms: Average Discounts",
  },

  {
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "From the Publishers: Collecting Accounts",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "Do Retail Florists Make Money?: A Path to Profits",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 4,
    name: "You & Your Corporation: How's the Relationship Going?",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 6,
    name: "Money Smarts: Savings Strategies",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 7,
    name: "By the Books: Gift Card Accounting: Do It Right",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "Inquiries & Answers: Order Accuracy",
  },
  {
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "Inquiries & Answers: Training New-hires",
  },
  { fileCore: "floral-finance-april-2022", page: 8, name: "Norms: Lost Sales" },

  {
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "From the Publishers: Success",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "House Accounts: Part 2: The Mechanics Matter",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 4,
    name: "Evaluating Advertising: Making Your Investment Pay",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 6,
    name: "By the Books: Traditional Wedding Protocol: A Checklist for Guidance",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Inquiries & Answers: Shoplifting",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Inquiries & Answers: Part-Time Space",
  },
  {
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Norms: Advertising Spend",
  },

  {
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "From the Publishers: Inertia",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "House Accounts: Part 1: When Should You Extend Credit?",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 4,
    name: "Shop Profile: Making Money in February: One Florist’s strokeStyle",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 6,
    name: "Finding the Help You Need: The Challenge—the Solution",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 7,
    name: "By the Books: Punching in Early … Staying Late",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Inquiries & Answers: Loss Leaders",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Inquiries & Answers: Coupon Power",
  },
  {
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Norms: Other Expenses",
  },

  {
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "From the Publishers: Delegation",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "Your Business Review: There’s No Better Time",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 4,
    name: "Owning Your Building: Is It Practical?",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 6,
    name: "Credit Card Perks: Free Airline Travel",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 7,
    name: "By the Books: Tips on Managing Holiday Volume: Short on Space?",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Inquiries & Answers: Cash Flow",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Inquiries & Answers: Giving Away That Old Car",
  },
  {
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Norms: Monthly Sales",
  },

  {
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "From the Publishers: Learning Through Life",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "Financial Checklists: Take Care of Those You Care For",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 4,
    name: "Gift Cards, Gift Certificates: Real Moneymakers",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 6,
    name: "Guarding Your Profits: Opportunities or Threats?",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 7,
    name: "By the Books: ATM Tips",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "Inquiries & Answers: Managing Partnerships",
  },
  {
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "Inquiries & Answers: Speaking of Partnerships",
  },
  { fileCore: "floral-finance-december-2021", page: 8, name: "norms: over 60" },

  {
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "From the Publishers: Thoughts of Success",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "Name: "It's Payday! Is Everyoneit's payday! is everyone happy?",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 4,
    name: "'special' sales: are they even necessary?'",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 6,
    name: "capitalism: the many gifts of business",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 7,
    name: "by the books: wires-out service charges",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "inquiries & answers: inventory turns",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "inquiries & answers: pricing multiple deliveries",
  },
  {
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "norms: gift sales",
  },

  {
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "from the publishers: getting people to listen",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "giving away the store: how to account for it",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 4,
    name: "managing the holidays: take time to get ready",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 6,
    name: "opportunities of a certain age: for your top & bottom lines",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 7,
    name: "by the books: pricing expensive flowers",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "inquiries & answers: used computers",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "inquiries & answers: internet advertising",
  },
  {
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "norms: amazon sales",
  },

  {
    fileCore: "floral-finance-september-2021",
    page: 2,
    name: "from the publishers: are there benefits to anger?",
  },
  {
    fileCore: "floral-finance-september-2021",
    page: 2,
    name: "selling by the stem: join the bandwagon",
  },
  {
    fileCore: "floral-finance-september-2021",
    page: 4,
    name: "one customer, two sales: an easier way to increase volume",
  },
  {
    fileCore: "floral-finance-september-2021",
    page: 6,
    name: "paying for layoffs",
  },
  {
    fileCore: "floral-finance-september-2021",
    page: 7,
    name: "by the books: help your accountant: you're not a retailer",
  },
  {
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "inquiries & answers: honoring expired coupons",
  },
  {
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "inquiries & answers: inventorying fresh flowers",
  },
  {
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "norms: fresh flowers & greens",
  },

  {
    fileCore: "floral-finance-august-2021",
    page: 2,
    name: "from the publishers: relationships",
  },
  {
    fileCore: "floral-finance-august-2021",
    page: 2,
    name: "is contract labor a good idea? how do i know if it's legal to hire contract drivers?",
  },
  {
    fileCore: "floral-finance-august-2021",
    page: 4,
    name: "facing a financial crisis",
  },
  {
    fileCore: "floral-finance-august-2021",
    page: 6,
    name: "employee discounts: a low-cost benefit your employees will love",
  },
  {
    fileCore: "floral-finance-august-2021",
    page: 7,
    name: "by the books: the numbers on contract labor",
  },
  {
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "inquiries & answers: too much rent",
  },
  {
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "inquiries & answers: ringing up incoming wire orders",
  },
  {
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "norms: sales increase",
  },
];
