const ff = [
  { downloadTitle: "floral-finance-july-2022" },
  { downloadTitle: "floral-finance-june-2022" },
  { downloadTitle: "floral-finance-may-2022" },
  { downloadTitle: "floral-finance-april-2022" },
  { downloadTitle: "floral-finance-march-2022" },
  { downloadTitle: "floral-finance-february-2022" },
  { downloadTitle: "floral-finance-january-2022" },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];

const articles = [
  {"DATE"0722.2", "from the publishers: looking back ... looking ahead"},
  {"DATE"0722.2", "cash flow: now is the time to plan"},
  {"DATE"0722.4", "cash flow forecasting: knowledge is power"},
  {"DATE"0722.6", "cut your payroll: key to seasoned success"},
  {"DATE"0722.7", "by the books: non-holiday staffing analysis—know what you can afford"},
  {"DATE"0722.8", "inquiries & answers: entertaining children"},
  {"DATE"0722.8", "inquiries & answers: august cash"},
  {"DATE"0722.8", "norms: shrink"},

  {"DATE"0622.2", "from the publishers: the ethics of payables"},
  {"DATE"0622.2", "making money in the slow months: can it be done?"},
  {"DATE"0622.4", "your business plan: the how & the why"},
  {"DATE"0622.6", "the family business: perks—getting something for nothing"},
  {"DATE"0622.7", "by the books: smart buying—a key to profitability"},
  {"DATE"0622.8", "inquiries & answers: paid holidays for employees"},
  {"DATE"0622.8", "inquiries & answers: teaching old dogs"},
  {"DATE"0622.8", "norms: sales from floral"}, 
  
  {"DATE"0522.2", "from the publishers: effective collections"},
  {"DATE"0522.2", "thinking on the margin: a lesson from hockey"},
  {"DATE"0522.4", "$776,487 in sales: $2,830 in profit"},
  {"DATE"0522.6", "the family business: family relationships"},
  {"DATE"0522.7", "by the books: your advertising budget—allocating advertising dollars"},
  {"DATE"0522.8", "inquiries & answers: low-cost mortgages"},
  {"DATE"0522.8", "inquiries & answers: liability protection"},
  {"DATE"0522.8", "norms: average discounts"}, 

  {"DATE"0422.2", "from the publishers: collecting accounts"}  
  {"DATE"0422.2", "do retail florists make money?: a path to profits"},
  {"DATE"0422.4", "you & your corporation: how's the relationship going?"},
  {"DATE"0422.6", "money smarts: savings strategies"},
  {"DATE"0422.7", "by the books: gift card accounting: do it right"},
  {"DATE"0422.8", "inquiries & answers: order accuracy"},
  {"DATE"0422.8", "inquiries & answers: training new-hires"},
  {"DATE"0422.8", "norms: lost sales"}, 

  {"DATE"0322.2", "from the publishers: success"},
  {"DATE"0322.2", "house accounts: part 2: the mechanics matter"},
  {"DATE"0322.4", "evaluating advertising: making your investment pay"},
  {"DATE"0322.6", "by the books: traditional wedding protocol: a checklist for guidance"},
  {"DATE"0322.8", "inquiries & answers: shoplifting"},
  {"DATE"0322.8", "inquiries & answers: part-time space"},
  {"DATE"0322.8", "norms: advertising spend"}, 

  {"DATE"0222.2", "from the publishers: inertia"},
  {"DATE"0222.2", "house accounts: part 1: when should you extend credit?"},
  {"DATE"0222.4", "shop profile: making money in february: one florist’s story"},
  {"DATE"0222.6", "finding the help you need: the challenge—the solution"},
  {"DATE"0222.7", "by the books: punching in early … staying late"},
  {"DATE"0222.8", "inquiries & answers: loss leaders"},
  {"DATE"0222.8", "inquiries & answers: coupon power"},
  {"DATE"0222.8", "norms: other expenses"}, 
  {"DATE"0122.2", "from the publishers: delegation"},
  {"DATE"0122.2", "your business review: there’s no better time"},
  {"DATE"0122.4", "owning your building: is it practical?"},
  {"DATE"0122.6", "credit card perks: free airline travel"},
  {"DATE"0122.7", "by the books: tips on managing holiday volume: short on space?"},
  {"DATE"0122.8", "inquiries & answers: cash flow"},
  {"DATE"0122.8", "inquiries & answers: giving away that old car"},
  {"DATE"0122.8", "norms: monthly sales"},
];
