const ff = [
    ["0722.2", "from the publishers: looking back ... looking ahead"], 
    ["0722.2", "cash flow: now is the time to plan"], 
    ["0722.4", "cash flow forecasting: knowledge is power"],
    ["0722.6", "cut your payroll: key to seasoned success"],
    ["0722.7", "by the books: non-holiday staffing analysis—know what you can afford"],, 
    ["0722.8", "inquiries & answers: entertaining children"],
    ["0722.8", "inquiries & answers: august cash"],
    ["0722.8", "norms: shrink"],
    
    ["0622.2", "from the publishers: the ethics of payables"], 
    ["0622.2", "making money in the slow months: can it be done?"], 
    ["0622.4", "your business plan: the how & the why"],
    [0"622.6", "the family business: perks—getting something for nothing"],
    ["0622.7", "by the books: smart buying—a key to profitability"],
    ["0622.8", "inquiries & answers: paid holidays for employees"],
    ["0622.8", "inquiries & answers: teaching old dogs"],
    ["0622.8", "norms: sales from floral"]

    ["0522.2", "from the publishers: effective collections"], 
    ["0522.2", "thinking on the margin: a lesson from hockey"], 
    ["0522.4", "$776,487 in sales: $2,830 in profit"],
    ["0522.6", "the family business: family relationships"],
    ["0522.7", "by the books: your advertising budget—allocating advertising dollars"],
    ["0522.8", "inquiries & answers: low-cost mortgages"],
    ["0522.8", "inquiries & answers: liability protection"],
    ["0522.8", "norms: average discounts"]

    ["0422.2", "from the publishers: collecting accounts"], 
    ["0422.2", "do retail florists make money?: a path to profits"], 
    ["0422.4", "you & your corporation: how's the relationship going?"],
    ["0422.6", "money smarts: savings strategies"],
    ["0422.7", "by the books: gift card accounting: do it right"],
    ["0422.8", "inquiries & answers: order accuracy"],
    ["0422.8", "inquiries & answers: training new-hires"],
    ["0422.8", "norms: lost sales"]

    ["0322.2", "from the publishers: success"], 
    ["0322.2", "house accounts: part 2: the mechanics matter"], 
    ["0322.4", "evaluating advertising: making your investment pay"],
    ["0322.6", "by the books: traditional wedding protocol: a checklist for guidance"],
    ["0322.8", "inquiries & answers: shoplifting"],
    ["0322.8", "inquiries & answers: part-time space"],
    ["0322.8", "norms: advertising spend"]

    ["0222.2", "from the publishers: inertia"], 
    ["0222.2", "house accounts: part 1: when should you extend credit?"], 
    ["0222.4", "shop profile: making money in february: one florist’s story"],
    ["0222.6", "finding the help you need: the challenge—the solution"],
    ["0222.7", "by the books: punching in early … staying late"],
    ["0222.8", "inquiries & answers: loss leaders"],
    ["0222.8", "inquiries & answers: coupon power"],
    ["0222.8", "norms: advertising spend"]




]




    downloadTitle: "floral-finance-february-2022",
    line2: [
      "from the publishers: inertia",
      "house accounts: part 1: when should you extend credit?",
    ],
    line4: "shop profile: making money in february: one florist’s story",
    line6: "finding the help you need: the challenge—the solution",
    line7: "by the books: punching in early … staying late",
    line8: [
      "inquiries & answers: loss leaders; coupon power",
      "norms: other expenses",
    ],
  },
  {
    downloadTitle: "floral-finance-january-2022",
    line2: [
      "from the publishers: delegation",
      "your business review: there’s no better time",
    ],
    line4: "owning your building: is it practical?",
    line6: "credit card perks: free airline travel",
    line7: "by the books: tips on managing holiday volume: short on space?",
    line8: [
      "inquiries & answers: cash flow; giving away that old car",
      "norms: monthly sales",
    ],
  },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];
