const ff = [
  { downloadTitle: "floral-finance-july-2022" },
  { downloadTitle: "floral-finance-june-2022" },
  { downloadTitle: "floral-finance-may-2022" },
  { downloadTitle: "floral-finance-april-2022" },
  { downloadTitle: "floral-finance-march-2022" },
  { downloadTitle: "floral-finance-february-2022" },
  { downloadTitle: "floral-finance-january-2022" },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];

const articles = [
  {
    name: "July 2022", 
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "From the Publishers: Looking Back ... Looking Ahead",
  },
  {
    name: "July 2022", 
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "Cash Flow: Now Is the Time to Plan",
  },
  {
    name: "July 2022", 
    fileCore: "floral-finance-july-2022",
    page: 4,
    name: "Cash Flow Forecasting: Knowledge Is Power",
  },
  {
    name: "July 2022", 
    fileCore: "floral-finance-july-2022",
    page: 6,
    name: "Cut Your Payroll: Key to Seasoned Success",
  },
  {
    name: "July 2022", 
    fileCore: "floral-finance-july-2022",
    page: 7,
    name: "By the Books: Non-Holiday Staffing Analysis—Know What You Can Afford",
  },
  {
    name: "July 2022", 
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: Entertaining Children",
  },
  {
    name: "July 2022", 
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: August Cash",
  },
  { fileCore: "floral-finance-july-2022", page: 8, name: "Norms: Shrink" },

  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "From the Publishers: The Ethics of Payables",
  },
  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "Making Money in the Slow Months: Can It Be Done?",
  },
  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 4,
    name: "Your Business Plan: The How & the Why",
  },
  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 6,
    name: "The Family Business: Perks—Getting Something for Nothing",
  },
  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 7,
    name: "By the Books: Smart Buying—a Key to Profitability",
  },
  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Inquiries & Answers: Paid Holidays for Employees",
  },
  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Inquiries & Answers: Teaching Old Dogs",
  },
  {
    name: "June 2022", 
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Norms: Sales From Floral",
  },

  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "From the Publishers: Effective Collections",
  },
  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "Thinking on the Margin: A Lesson From Hockey",
  },
  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 4,
    name: "$776,487 in Sales: $2,830 in Profit",
  },
  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 6,
    name: "The Family Business: Family Relationships",
  },
  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 7,
    name: "By the Books: Your Advertising Budget—Allocating Advertising Dollars",
  },
  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Inquiries & Answers: Low-Cost Mortgages",
  },
  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Inquiries & Answers: Liability Protection",
  },
  {
    name: "May 2022", 
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Norms: Average Discounts",
  },

  {
    name: "April 2022", 
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "From the Publishers: Collecting Accounts",
  },
  {
    name: "April 2022", 
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "Do Retail Florists Make Money?: A Path to Profits",
  },
  {
    name: "April 2022", 
    fileCore: "floral-finance-april-2022",
    page: 4,
    name: "You & Your Corporation: How's the Relationship Going?",
  },
  {
    name: "April 2022", 
    fileCore: "floral-finance-april-2022",
    page: 6,
    name: "Money Smarts: Savings Strategies",
  },
  {
    name: "April 2022", 
    fileCore: "floral-finance-april-2022",
    page: 7,
    name: "By the Books: Gift Card Accounting: Do It Right",
  },
  {
    name: "April 2022", 
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "Inquiries & Answers: Order Accuracy",
  },
  {
    name: "April 2022", 
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "Inquiries & Answers: Training New-hires",
  },
  { name: "April 2022", 
    fileCore: "floral-finance-april-2022", page: 8, name: "Norms: Lost Sales" },

  {
    name: "March 2022", 
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "From the Publishers: Success",
  },
  {
    name: "March 2022", 
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "House Accounts: Part 2: The Mechanics Matter",
  },
  {
    name: "March 2022", 
    fileCore: "floral-finance-march-2022",
    page: 4,
    name: "Evaluating Advertising: Making Your Investment Pay",
  },
  {
    name: "March 2022", 
    fileCore: "floral-finance-march-2022",
    page: 6,
    name: "By the Books: Traditional Wedding Protocol: A Checklist for Guidance",
  },
  {
    name: "March 2022", 
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Inquiries & Answers: Shoplifting",
  },
  {
    name: "March 2022", 
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Inquiries & Answers: Part-Time Space",
  },
  {
    name: "March 2022", 
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Norms: Advertising Spend",
  },

  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "From the Publishers: Inertia",
  },
  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "House Accounts: Part 1: When Should You Extend Credit?",
  },
  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 4,
    name: "Shop Profile: Making Money in February: One Florist’s strokeStyle",
  },
  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 6,
    name: "Finding the Help You Need: The Challenge—the Solution",
  },
  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 7,
    name: "By the Books: Punching in Early … Staying Late",
  },
  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Inquiries & Answers: Loss Leaders",
  },
  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Inquiries & Answers: Coupon Power",
  },
  {
    name: "February 2022", 
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Norms: Other Expenses",
  },

  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "From the Publishers: Delegation",
  },
  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "Your Business Review: There’s No Better Time",
  },
  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 4,
    name: "Owning Your Building: Is It Practical?",
  },
  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 6,
    name: "Credit Card Perks: Free Airline Travel",
  },
  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 7,
    name: "By the Books: Tips on Managing Holiday Volume: Short on Space?",
  },
  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Inquiries & Answers: Cash Flow",
  },
  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Inquiries & Answers: Giving Away That Old Car",
  },
  {
    name: "January 2022", 
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Norms: Monthly Sales",
  },

  {
    name: "J 2021", 
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "From the Publishers: Learning Through Life",
  },
  {
    name: "J 2021", 
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "Financial Checklists: Take Care of Those You Care For",
  },
  {
    name: "J 2021", 
    fileCore: "floral-finance-december-2021",
    page: 4,
    name: "Gift Cards, Gift Certificates: Real Moneymakers",
  },
  {
    name: "J 2021", 
    fileCore: "floral-finance-december-2021",
    page: 6,
    name: "Guarding Your Profits: Opportunities or Threats?",
  },
  {
    name: "J 2021", 
    fileCore: "floral-finance-december-2021",
    page: 7,
    name: "By the Books: ATM Tips",
  },
  {
    name: "J 2021", 
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "Inquiries & Answers: Managing Partnerships",
  },
  {
    name: "J 2021", 
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "Inquiries & Answers: Speaking of Partnerships",
  },
  { name: "J 2021", 
    fileCore: "floral-finance-december-2021", page: 8, name: "norms: over 60" },

  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "From the Publishers: Thoughts of Success",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "It's Payday! Is Everyone Happy?",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 4,
    name: "'Special' Sales: Are They Even Necessary?'",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 6,
    name: "Capitalism: The Many Gifts of Business",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 7,
    name: "January 2021", 
    name: "By the Books: Wires-Out Service Charges",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "Inquiries & Answers: Inventory Turns",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "Inquiries & Answers: Pricing Multiple Deliveries",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "Norms: Gift Sales",
  },

  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "From the Publishers: Getting People to Listen",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "Giving Away the Store: How to Account for It",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 4,
    name: "Managing the Holidays: Take Time to Get Ready",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 6,
    name: "Opportunities of a Certain Age: For Your Top & Bottom Lines",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 7,
    name: "By the Books: Pricing Expensive Flowers",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "Inquiries & Answers: Used Computers",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "Inquiries & Answers: Internet Advertising",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "Norms: Amazon Sales",
  },

  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 2,
    name: "From the Publishers: Are There Benefits to Anger?",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 2,
    name: "Selling by the Stem: Join the Bandwagon",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 4,
    name: "One Customer, Two Sales: An Easier Way to Increase Volume",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 6,
    name: "Paying for Layoffs",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 7,
    name: "By the Books: Help Your Accountant: You're Not a Retailer",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "Inquiries & Answers: Honoring Expired Coupons",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "Inquiries & Answers: Inventorying Fresh Flowers",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "Norms: Fresh Flowers & Greens",
  },

  {
    name: "January 2021", 
    fileCore: "floral-finance-august-2021",
    page: 2,
    name: "From the Publishers: Relationships",
  },
  {
    name: "January 2021", f
    ileCore: "floral-finance-august-2021",
    page: 2,
    name: "Is Contract Labor a Good Idea? How Do I Know if It's Legal to Hire Contract Drivers?",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-august-2021",
    page: 4,
    name: "Facing a Financial Crisis",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-august-2021",
    page: 6,
    name: "Employee Discounts: A Low-Cost Benefit Your Employees Will Love",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-august-2021",
    page: 7,
    name: "By the Books: The Numbers on Contract Labor",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "Inquiries & Answers: Too Much Rent",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "Inquiries & Answers: Ringing Up Incoming Wire Orders",
  },
  {
    name: "January 2021", 
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "Norms: Sales Increase",
  },
];
