const ff = [
  { downloadTitle: "floral-finance-july-2022" },
  { downloadTitle: "floral-finance-june-2022" },
  { downloadTitle: "floral-finance-may-2022" },
  { downloadTitle: "floral-finance-april-2022" },
  { downloadTitle: "floral-finance-march-2022" },
  { downloadTitle: "floral-finance-february-2022" },
  { downloadTitle: "floral-finance-january-2022" },
  { downloadTitle: "floral-finance-december-2021" },
  { downloadTitle: "floral-finance-november-2021" },
  { downloadTitle: "floral-finance-october-2021" },
  { downloadTitle: "floral-finance-september-2021" },
  { downloadTitle: "floral-finance-august-2021" },
  { downloadTitle: "floral-finance-july-2021" },
  { downloadTitle: "floral-finance-june-2021" },
  { downloadTitle: "floral-finance-may-2021" },
  { downloadTitle: "floral-finance-april-2021" },
  { downloadTitle: "floral-finance-march-2021" },
  { downloadTitle: "floral-finance-february-2021" },
  { downloadTitle: "floral-finance-january-2021" },
  { downloadTitle: "floral-finance-december-2020" },
  { downloadTitle: "floral-finance-november-2020" },
  { downloadTitle: "floral-finance-october-2020" },
  { downloadTitle: "floral-finance-september-2020" },
  { downloadTitle: "floral-finance-august-2020" },
  { downloadTitle: "floral-finance-july-2020" },
  { downloadTitle: "floral-finance-june-2020" },
  { downloadTitle: "floral-finance-may-2020" },
  { downloadTitle: "floral-finance-april-2020" },
  { downloadTitle: "floral-finance-march-2020" },
  { downloadTitle: "floral-finance-february-2020" },
  { downloadTitle: "floral-finance-january-2020" },
  { downloadTitle: "floral-finance-december-2019" },
  { downloadTitle: "floral-finance-november-2019" },
  { downloadTitle: "floral-finance-october-2019" },
  { downloadTitle: "floral-finance-september-2019" },
  { downloadTitle: "floral-finance-august-2019" },
  { downloadTitle: "floral-finance-july-2019" },
  { downloadTitle: "floral-finance-june-2019" },
  { downloadTitle: "floral-finance-may-2019" },
  { downloadTitle: "floral-finance-april-2019" },
  { downloadTitle: "floral-finance-march-2019" },
  { downloadTitle: "floral-finance-february-2019" },
  { downloadTitle: "floral-finance-january-2019" },
  { downloadTitle: "floral-finance-december-2018" },
  { downloadTitle: "floral-finance-november-2018" },
  { downloadTitle: "floral-finance-october-2018" },
  { downloadTitle: "floral-finance-september-2018" },
  { downloadTitle: "floral-finance-august-2018" },
  { downloadTitle: "floral-finance-july-2018" },
  { downloadTitle: "floral-finance-june-2018" },
  { downloadTitle: "floral-finance-may-2018" },
  { downloadTitle: "floral-finance-april-2018" },
  { downloadTitle: "floral-finance-march-2018" },
  { downloadTitle: "floral-finance-february-2018" },
  { downloadTitle: "floral-finance-january-2018" },
  { downloadTitle: "floral-finance-december-2017" },
  { downloadTitle: "floral-finance-november-2017" },
  { downloadTitle: "floral-finance-october-2017" },
  { downloadTitle: "floral-finance-september-2017" },
  { downloadTitle: "floral-finance-august-2017" },
  { downloadTitle: "floral-finance-july-2017" },
  { downloadTitle: "floral-finance-june-2017" },
  { downloadTitle: "floral-finance-may-2017" },
  { downloadTitle: "floral-finance-april-2017" },
  { downloadTitle: "floral-finance-march-2017" },
  { downloadTitle: "floral-finance-february-2017" },
  { downloadTitle: "floral-finance-january-2017" },
  { downloadTitle: "floral-finance-december-2016" },
  { downloadTitle: "floral-finance-november-2016" },
  { downloadTitle: "floral-finance-october-2016" },
  { downloadTitle: "floral-finance-september-2016" },
  { downloadTitle: "floral-finance-august-2016" },
  { downloadTitle: "floral-finance-july-2016" },
  { downloadTitle: "floral-finance-june-2016" },
  { downloadTitle: "floral-finance-may-2016" },
  { downloadTitle: "floral-finance-april-2016" },
  { downloadTitle: "floral-finance-march-2016" },
  { downloadTitle: "floral-finance-february-2016" },
  { downloadTitle: "floral-finance-january-2016" },
  { downloadTitle: "floral-finance-december-2015" },
  { downloadTitle: "floral-finance-november-2015" },
  { downloadTitle: "floral-finance-october-2015" },
  { downloadTitle: "floral-finance-september-2015" },
];

const articles = [
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "From the Publishers: Looking Back ... Looking Ahead",
  },
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 2,
    name: "Cash Flow: Now Is the Time to Plan",
  },
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 4,
    name: "Cash Flow Forecasting: Knowledge Is Power",
  },
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 6,
    name: "Cut Your Payroll: Key to Seasoned Success",
  },
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 7,
    name: "By the Books: Non-Holiday Staffing Analysis—Know What You Can Afford",
  },
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: Entertaining Children",
  },
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Inquiries & Answers: August Cash",
  },
  {
    date: "July 2022",
    fileCore: "floral-finance-july-2022",
    page: 8,
    name: "Norms: Shrink",
  },

  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "From the Publishers: The Ethics of Payables",
  },
  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 2,
    name: "Making Money in the Slow Months: Can It Be Done?",
  },
  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 4,
    name: "Your Business Plan: The How & the Why",
  },
  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 6,
    name: "The Family Business: Perks—Getting Something for Nothing",
  },
  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 7,
    name: "By the Books: Smart Buying—a Key to Profitability",
  },
  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Inquiries & Answers: Paid Holidays for Employees",
  },
  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Inquiries & Answers: Teaching Old Dogs",
  },
  {
    date: "June 2022",
    fileCore: "floral-finance-june-2022",
    page: 8,
    name: "Norms: Sales From Floral",
  },

  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "From the Publishers: Effective Collections",
  },
  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 2,
    name: "Thinking on the Margin: A Lesson From Hockey",
  },
  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 4,
    name: "$776,487 in Sales: $2,830 in Profit",
  },
  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 6,
    name: "The Family Business: Family Relationships",
  },
  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 7,
    name: "By the Books: Your Advertising Budget—Allocating Advertising Dollars",
  },
  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Inquiries & Answers: Low-Cost Mortgages",
  },
  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Inquiries & Answers: Liability Protection",
  },
  {
    date: "May 2022",
    fileCore: "floral-finance-may-2022",
    page: 8,
    name: "Norms: Average Discounts",
  },

  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "From the Publishers: Collecting Accounts",
  },
  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 2,
    name: "Do Retail Florists Make Money?: A Path to Profits",
  },
  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 4,
    name: "You & Your Corporation: How's the Relationship Going?",
  },
  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 6,
    name: "Money Smarts: Savings Strategies",
  },
  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 7,
    name: "By the Books: Gift Card Accounting: Do It Right",
  },
  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "Inquiries & Answers: Order Accuracy",
  },
  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "Inquiries & Answers: Training New-hires",
  },
  {
    date: "April 2022",
    fileCore: "floral-finance-april-2022",
    page: 8,
    name: "Norms: Lost Sales",
  },

  {
    date: "March 2022",
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "From the Publishers: Success",
  },
  {
    date: "March 2022",
    fileCore: "floral-finance-march-2022",
    page: 2,
    name: "House Accounts: Part 2: The Mechanics Matter",
  },
  {
    date: "March 2022",
    fileCore: "floral-finance-march-2022",
    page: 4,
    name: "Evaluating Advertising: Making Your Investment Pay",
  },
  {
    date: "March 2022",
    fileCore: "floral-finance-march-2022",
    page: 6,
    name: "By the Books: Traditional Wedding Protocol: A Checklist for Guidance",
  },
  {
    date: "March 2022",
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Inquiries & Answers: Shoplifting",
  },
  {
    date: "March 2022",
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Inquiries & Answers: Part-Time Space",
  },
  {
    date: "March 2022",
    fileCore: "floral-finance-march-2022",
    page: 8,
    name: "Norms: Advertising Spend",
  },

  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "From the Publishers: Inertia",
  },
  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 2,
    name: "House Accounts: Part 1: When Should You Extend Credit?",
  },
  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 4,
    name: "Shop Profile: Making Money in February: One Florist’s strokeStyle",
  },
  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 6,
    name: "Finding the Help You Need: The Challenge—the Solution",
  },
  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 7,
    name: "By the Books: Punching in Early … Staying Late",
  },
  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Inquiries & Answers: Loss Leaders",
  },
  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Inquiries & Answers: Coupon Power",
  },
  {
    date: "February 2022",
    fileCore: "floral-finance-february-2022",
    page: 8,
    name: "Norms: Other Expenses",
  },

  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "From the Publishers: Delegation",
  },
  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 2,
    name: "Your Business Review: There’s No Better Time",
  },
  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 4,
    name: "Owning Your Building: Is It Practical?",
  },
  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 6,
    name: "Credit Card Perks: Free Airline Travel",
  },
  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 7,
    name: "By the Books: Tips on Managing Holiday Volume: Short on Space?",
  },
  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Inquiries & Answers: Cash Flow",
  },
  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Inquiries & Answers: Giving Away That Old Car",
  },
  {
    date: "January 2022",
    fileCore: "floral-finance-january-2022",
    page: 8,
    name: "Norms: Monthly Sales",
  },

  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "From the Publishers: Learning Through Life",
  },
  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 2,
    name: "Financial Checklists: Take Care of Those You Care For",
  },
  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 4,
    name: "Gift Cards, Gift Certificates: Real Moneymakers",
  },
  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 6,
    name: "Guarding Your Profits: Opportunities or Threats?",
  },
  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 7,
    name: "By the Books: ATM Tips",
  },
  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "Inquiries & Answers: Managing Partnerships",
  },
  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "Inquiries & Answers: Speaking of Partnerships",
  },
  {
    date: "December 2021",
    fileCore: "floral-finance-december-2021",
    page: 8,
    name: "norms: over 60",
  },

  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "From the Publishers: Thoughts of Success",
  },
  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 2,
    name: "It's Payday! Is Everyone Happy?",
  },
  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 4,
    name: "'Special' Sales: Are They Even Necessary?'",
  },
  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 6,
    name: "Capitalism: The Many Gifts of Business",
  },
  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 7,
    name: "November 2021",
    name: "By the Books: Wires-Out Service Charges",
  },
  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "Inquiries & Answers: Inventory Turns",
  },
  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "Inquiries & Answers: Pricing Multiple Deliveries",
  },
  {
    date: "November 2021",
    fileCore: "floral-finance-november-2021",
    page: 8,
    name: "Norms: Gift Sales",
  },

  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "From the Publishers: Getting People to Listen",
  },
  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 2,
    name: "Giving Away the Store: How to Account for It",
  },
  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 4,
    name: "Managing the Holidays: Take Time to Get Ready",
  },
  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 6,
    name: "Opportunities of a Certain Age: For Your Top & Bottom Lines",
  },
  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 7,
    name: "By the Books: Pricing Expensive Flowers",
  },
  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "Inquiries & Answers: Used Computers",
  },
  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "Inquiries & Answers: Internet Advertising",
  },
  {
    date: "October 2021",
    fileCore: "floral-finance-october-2021",
    page: 8,
    name: "Norms: Amazon Sales",
  },

  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 2,
    name: "From the Publishers: Are There Benefits to Anger?",
  },
  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 2,
    name: "Selling by the Stem: Join the Bandwagon",
  },
  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 4,
    name: "One Customer, Two Sales: An Easier Way to Increase Volume",
  },
  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 6,
    name: "Paying for Layoffs",
  },
  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 7,
    name: "By the Books: Help Your Accountant: You're Not a Retailer",
  },
  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "Inquiries & Answers: Honoring Expired Coupons",
  },
  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "Inquiries & Answers: Inventorying Fresh Flowers",
  },
  {
    date: "September 2021",
    fileCore: "floral-finance-september-2021",
    page: 8,
    name: "Norms: Fresh Flowers & Greens",
  },

  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 2,
    name: "From the Publishers: Relationships",
  },
  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 2,
    name: "Is Contract Labor a Good Idea? How Do I Know if It's Legal to Hire Contract Drivers?",
  },
  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 4,
    name: "Facing a Financial Crisis",
  },
  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 6,
    name: "Employee Discounts: A Low-Cost Benefit Your Employees Will Love",
  },
  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 7,
    name: "By the Books: The Numbers on Contract Labor",
  },
  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "Inquiries & Answers: Too Much Rent",
  },
  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "Inquiries & Answers: Ringing Up Incoming Wire Orders",
  },
  {
    date: "August 2021",
    fileCore: "floral-finance-august-2021",
    page: 8,
    name: "Norms: Sales Increase",
  },

  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 2,
    name: "From the Publishers: Looking Back ... Looking Ahead",
  },
  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 2,
    name: "Cash Flow: Now Is the Time to Plan",
  },
  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 4,
    name: "Cash Flow Forecasting: Knowledge Is Power",
  },
  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 6,
    name: "Cut Your Payroll: Key to Seasoned Success",
  },
  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 7,
    name: "By the Books: Non-Holiday Staffing Analysis—Know What You Can Afford",
  },
  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 8,
    name: "Inquiries & Answers: Entertaining Children",
  },
  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 8,
    name: "Inquiries & Answers: August Cash",
  },
  {
    date: "July 2021",
    fileCore: "floral-finance-july-2021",
    page: 8,
    name: "Norms: Shrink",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 2,
    name: "From the Publishers: Determination",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 2,
    name: "Looking for Cash? Surviving the Summer Slowdown",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 4,
    name: "Retail Marketing & Sales 101: Visit a Local Convenience Store",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 6,
    name: "Part-Time Help: Blessing or Bane?",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 7,
    name: "Part-Time Help: Management Issues to Consider",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 8,
    name: "Inquiries & Answers: Counterfeit Money",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 8,
    name: "Inquiries & Answers: Mid-Year Inventory",
  },
  {
    date: "June 2021",
    fileCore: "floral-finance-june-2021",
    page: 8,
    name: "Norms: Non-Holiday Months",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 2,
    name: "From the Publishers: Build Customer Loyalty",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 2,
    name: "Free Publicity: Economical Public Relations",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 4,
    name: "Time & Task Management: A Host of Problems",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 6,
    name: "Extending Your Hours: 24 Hour Flowers Makes It Easy",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 7,
    name: "By the Books: Is It Time to Hire?",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 8,
    name: "Inquiries & Answers: Don't Withhold",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 8,
    name: "Inquiries & Answers: Eternal Loans",
  },
  {
    date: "May 2021",
    fileCore: "floral-finance-may-2021",
    page: 8,
    name: "Norms: Delivery Sales",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 2,
    name: "From the Publishers: Choices",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 2,
    name: "Charging for Non-Design Labor: Weddings, Events, Decorating & Parties",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 4,
    name: "Pricing Formulas for Weddings: What's the Best Approach?",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 6,
    name: "Marketing Incoming Wire Orders",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 7,
    name: "By the Books: Paying for College",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 8,
    name: "Inquiries & Answers: Sharing the Load",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 8,
    name: "Inquiries & Answers: Partnership Fundamentals",
  },
  {
    date: "April 2021",
    fileCore: "floral-finance-april-2021",
    page: 8,
    name: "Norms: Facilities Cost",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 2,
    name: "From the Publishers: Difficulties",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 2,
    name: "Screening Your Drivers: How Much Can You Trust?",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 4,
    name: "How to Manage Right-Brained Designers: A Delicate Balance",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 6,
    name: "Taxing the Internet: Access VS. Purchases",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 7,
    name: "By the Books: To Deduct or Not: Wage & Hour Law",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 8,
    name: "Inquiries & Answers: Paying Yourself",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 8,
    name: "Inquiries & Answers: Not Paying Yourself",
  },
  {
    date: "March 2021",
    fileCore: "floral-finance-march-2021",
    page: 8,
    name: "Norms: Small Expenses",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 2,
    name: "From the Publishers: You Can't Change a Tiger's Stripes",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 2,
    name: "Unclogging a Bottleneck: Efficiency is Money in the Bank",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 4,
    name: "The Express Delivery Option: Fast...Fast...Fast",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 6,
    name: "Identity Theft: An Ounce Prevention of",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 7,
    name: "By the Books: Finding Cash: Dead Assets Can Help",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 8,
    name: "Inquiries & Answers: To Audit or Not to Audit",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 8,
    name: "Inquiries & Answers: Criticism",
  },
  {
    date: "February 2021",
    fileCore: "floral-finance-february-2021",
    page: 8,
    name: "Norms: New Mileage Rate",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 2,
    name: "From the Publishers: Our Upside-Down World",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 2,
    name: "Direct-Response Marketing: The Greatest Return per Dollar Spent",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 4,
    name: "Gift Cards & Gift Certificates: A Real Moneymaker",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 6,
    name: "Email Marketing: Easy, Fast & Broad-Reaching",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 7,
    name: "By the Books: Proper Accounting for Cost of Goods Sold",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 8,
    name: "Inquiries & Answers: Features & Benefits,",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 8,
    name: "Inquiries & Answers: Naming an Executor",
  },
  {
    date: "January 2021",
    fileCore: "floral-finance-january-2021",
    page: 8,
    name: "Norms: Valentine's Day Pickups & Deliveries",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 2,
    name: "From the Publishers: Forced Changes",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 2,
    name: "Finding Cash When You Need It: It's a Challenge",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 4,
    name: "Sources of Cash: After Uncle Ernest & Aunt Hazel",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 6,
    name: "Payroll: Weekly, Biweekly or Semimonthly?",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 7,
    name: "By the Books: Using a Service Payroll",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 8,
    name: "Inquiries & Answers: Efficient Delivery,",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 8,
    name: "Inquiries & Answers: Holding on to Cash",
  },
  {
    date: "December 2020",
    fileCore: "floral-finance-december-2020",
    page: 8,
    name: "Norms: Online Sales",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 2,
    name: "From the Publishers: Model Your Vision",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 2,
    name: "A Shop Analysis: Why Do One?",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 4,
    name: "How Much Is My Business Worth?: Flower Shop Valuation",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 6,
    name: "Ruining a Great Customer: Too Much of a Good Thing?",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 7,
    name: "By the Books: Signing a Lease",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 8,
    name: "Inquiries & Answers: Payables",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 8,
    name: "Inquiries & Answers: Email Marketing",
  },
  {
    date: "November 2020",
    fileCore: "floral-finance-november-2020",
    page: 8,
    name: "Norms: Coupons",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 2,
    name: "From the Publishers: Be Thankful You're a Florist",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 2,
    name: "Selecting Your Site: Moving, Growing or Downsizing?",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 4,
    name: "The Multiple-Shop Paradigm: Perception Vs. Reality",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 6,
    name: "Company Cars: Perks & Potholes",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 7,
    name: "By the Books: Defining Sales",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 8,
    name: "Inquiries & Answers: Promoting Your Website",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 8,
    name: "Inquiries & Answers: E-Commerce Enabled",
  },
  {
    date: "October 2020",
    fileCore: "floral-finance-october-2020",
    page: 8,
    name: "Norms: Accounting",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 2,
    name: "From the Publishers: The Right Destination",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 2,
    name: "Non-Floral Products: Good for a Flower Shop?",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 4,
    name: "Estate Planning & Retail Florists: 'Old florists never die .. they just make other arrangements.'",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 6,
    name: "Collecting What's Due: Taking Your Customer to Court",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 7,
    name: "By the Books: Managing Bad Checks",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 8,
    name: "Inquiries & Answers: Freight Charges",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 8,
    name: "Inquiries & Answers: Sales Taxes",
  },
  {
    date: "September 2020",
    fileCore: "floral-finance-september-2020",
    page: 8,
    name: "Norms: Birth of the Internet",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 2,
    name: "From the Publishers: Perspective",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 2,
    name: "Satisfaction Guaranteed: How Important Is It?",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 4,
    name: "Sales Forecasting & Budgets: Two Vital Business Tools",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 6,
    name: "Wire Order Accounting: How Not to Do It",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 7,
    name: "By the Books: Wire Order Accounting: The Easiest Way",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 8,
    name: "Inquiries & Answers: Tax Records",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 8,
    name: "Inquiries & Answers: Charitable Contribution",
  },
  {
    date: "August 2020",
    fileCore: "floral-finance-august-2020",
    page: 8,
    name: "Norms: Closings & Opportunities",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 2,
    name: "From the Publishers: The Family-Owned Business",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 2,
    name: "Paycheck Protection Program Forgiveness: Major Updates",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 4,
    name: "Personal Guarantees in a Covid-19 World: Putting It All on the Line",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 6,
    name: "Net Profit: How Is My Business Really Doing?",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 7,
    name: "By the Books: Online Banking",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 8,
    name: "Inquiries & Answers: Wedding Flowers",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 8,
    name: "Inquiries & Answers: Roadside Vendors",
  },
  {
    date: "July 2020",
    fileCore: "floral-finance-july-2020",
    page: 8,
    name: "Norms: Website Traffic",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 2,
    name: "From the Publishers: What's Coming?",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 2,
    name: "Reopening Essentials",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 2,
    name: "A Reopening Checklist",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 4,
    name: "Staffing After Covid-19: Uncharted Waters",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 6,
    name: "Cash Is King: Forecasting Summer Cash Flow",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 8,
    name: "Inquiries & Answers: Vehicle Financing",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 8,
    name: "Inquiries & Answers: Summer Hours",
  },
  {
    date: "June 2020",
    fileCore: "floral-finance-june-2020",
    page: 8,
    name: "Norms: Standard Deliveries",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 2,
    name: "From the Publishers: Values in Critical Times",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 2,
    name: "Best Practices in a Crisis: 10 Things to Do First",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 4,
    name: "Profitability & Growth",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 4,
    name: "Acquiring & Maintaining Financial Control: All the Pieces Are Important",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 5,
    name: "Financials for Planning & Control: The Modified Accrual Method",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 7,
    name: "'Know Thyself': And Use That Knowledge for Profit",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 8,
    name: "Inquiries & Answers: Federal Loan Proceeds",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 8,
    name: "Inquiries & Answers: The Best Advertising",
  },
  {
    date: "May 2020",
    fileCore: "floral-finance-may-2020",
    page: 8,
    name: "Norms: Nothing",
  },
  {
    date: "April 2020",
    fileCore: "floral-finance-april-2020",
    page: 2,
    name: "From the Publishers: Count Your Blessings",
  },
  {
    date: "April 2020",
    fileCore: "floral-finance-april-2020",
    page: 2,
    name: "Getting a Good Report Card: How Well Are You Doing?",
  },
  {
    date: "April 2020",
    fileCore: "floral-finance-april-2020",
    page: 6,
    name: "OR Codes: They're Everywhere",
  },
  {
    date: "April 2020",
    fileCore: "floral-finance-april-2020",
    page: 7,
    name: "Charitable Contributions: Should You or Your Business Write the Check?",
  },
  {
    date: "April 2020",
    fileCore: "floral-finance-april-2020",
    page: 8,
    name: "Inquiries & Answers: Holiday Pay",
  },
  {
    date: "April 2020",
    fileCore: "floral-finance-april-2020",
    page: 8,
    name: "Inquiries & Answers: Cash Flow",
  },
  {
    date: "April 2020",
    fileCore: "floral-finance-april-2020",
    page: 8,
    name: "Norms: Arrangement Sales",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 2,
    name: "From the Publishers: What Do You Remember?",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 2,
    name: "Dissatisfied Customers: How Much Do They Cost You?",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 4,
    name: "Bankruptcy: A Blessing or a Curse?",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 6,
    name: "Holding Firm: Who's in Charge?",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 7,
    name: "By the Books: Fixing a Credit Report",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 8,
    name: "Inquiries & Answers: Risk vs. Return",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 8,
    name: "Inquiries & Answers: Deductions Vs. Credits",
  },
  {
    date: "March 2020",
    fileCore: "floral-finance-march-2020",
    page: 8,
    name: "Norms: Designer Wages",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 2,
    name: "From the Publishers: Reaching Your Goal",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 2,
    name: "The Trouble With Taxes: A Mix-up Could Cause You to Lose Your Shop",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 4,
    name: "Why Flower Shops Succeed",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 5,
    name: "Why Flower Shops Fail",
  },

  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 6,
    name: "Retirement Plans: What to Consider",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 7,
    name: "By the Books: Using Credit Cards to Pay Bill—Good or Bad Idea?",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 8,
    name: "Inquiries & Answers: Unsigned Checks",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 8,
    name: "Inquiries & Answers: Holding Onto Your Cash",
  },
  {
    date: "February 2020",
    fileCore: "floral-finance-february-2020",
    page: 8,
    name: "Norms: Website Awareness",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 2,
    name: "From the Publishers: Self-Image",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 2,
    name: "Credit Cards: Preventing Fraud",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 4,
    name: "Management Essentials: Forecasting Cash Flow.",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 6,
    name: "No Guts, No Glory: Traits of the Entrepreneur Successful",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 7,
    name: "By the Books: Business Insurance-What Do You Need?",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 8,
    name: "Inquiries & Answers: Pricing Sets",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 8,
    name: "Inquiries & Answers: Invoices or Statements",
  },
  {
    date: "January 2020",
    fileCore: "floral-finance-january-2020",
    page: 8,
    name: "Norms: Basic Rule",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 2,
    name: "From the Publishers: The Mainspring of Human Progress",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 2,
    name: "Management Essentials: Standard Arrangements",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 4,
    name: "Management Essentials: Special Containers-Are They Good for Retail Florists?",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 6,
    name: "Money Smarts: Using Credit Wisely",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 7,
    name: "By the Books: Cash Versus Accrual Accounting What's the Difference?",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 8,
    name: "Inquiries & Answers: Anonymous Deliveries",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 8,
    name: "Inquiries & Answers: Wedding Cancellations",
  },
  {
    date: "December 2019",
    fileCore: "floral-finance-december-2019",
    page: 8,
    name: "Norms: Holiday Volume",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 2,
    name: "From the Publishers: Increase Customer Loyalty",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 2,
    name: "When a Partner Leaves: Navigating a Split",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 4,
    name: "Management Essentials: Understanding Shrink Why It's Important",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 6,
    name: "Cutting Orders: Is It Ever Okay?.",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 7,
    name: "By the Books: Handling the Cost of Shrink.",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 8,
    name: "Inquiries & Answers: Computer Decisions",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 8,
    name: "Inquiries & Answers: Delivery Charges",
  },
  {
    date: "November 2019",
    fileCore: "floral-finance-november-2019",
    page: 8,
    name: "Norms: Apple Pay",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 2,
    name: "From the Publishers: Choices",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 2,
    name: "Management Essentials: Charging for Services: What & How Much?",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 4,
    name: "Designer Productivity: Why Does It Matter?",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 6,
    name: "Money Smarts: Saving Strategies",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 7,
    name: "By the Books: Charging for Labor",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 8,
    name: "Inquiries & Answers: Pricing Weekly Specials;",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 8,
    name: "Inquiries & Answers: Long-Distance Deliveries",
  },
  {
    date: "October 2019",
    fileCore: "floral-finance-october-2019",
    page: 8,
    name: "Norms: FTE Annual Sales",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 2,
    name: "From the Publishers: Forced Changes",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 2,
    name: "Management Essentials: Taking a Physical Inventory: Why Is It Necessary?",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 4,
    name: "Management Essentials: Price Barriers: Are You Using Them Wisely?",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 6,
    name: "Money Smarts: Is Your Goal to Be a Millionaire?",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 7,
    name: "By the Books: Loan Guarantees: What Are You Getting Yourself Into?",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 8,
    name: "Inquiries & Answers: Processing Payroll",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 8,
    name: "Inquiries & Answers: Raising Prices",
  },
  {
    date: "September 2019",
    fileCore: "floral-finance-september-2019",
    page: 8,
    name: "Norms: 65 Years of Age",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 2,
    name: "From the Publishers: A Business Idea",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 2,
    name: "Management Essentials: Inventory Management",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 4,
    name: "Management Essentials: Proper Inventory Accounting.",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 6,
    name: "Managing Your Money: On a Personal Note",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 7,
    name: "By the Books: Accountants & Bookkeepers: Maximize Their Use... Minimize the Cost",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 8,
    name: "Inquiries & Answers: Location",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 8,
    name: "Inquiries & Answers: Internet Options",
  },
  {
    date: "August 2019",
    fileCore: "floral-finance-august-2019",
    page: 8,
    name: "Norms: Mileage Rate.",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 2,
    name: "From the Publishers: How Do You View Your Employees?",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 2,
    name: "Management Essentials: Controlling The Payables: Joys & Challenges of Spending Money",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 4,
    name: "Management Essentials: Controlling Expenses: Every Dollar Goes to the Bottom Line",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 6,
    name: "Leadership for Financial Success: An Imperative Skill Set",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 7,
    name: "By the Books: Direct Orders: Pros & Cons",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 8,
    name: "Inquiries & Answers: Delivery Zones",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 8,
    name: "Inquiries & Answers: Leaving Flowers",
  },
  {
    date: "July 2019",
    fileCore: "floral-finance-july-2019",
    page: 8,
    name: "Norms: Employees",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 2,
    name: "From the Publishers: What's Your Purpose?",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 2,
    name: "Why Customers Don't Pay: Knowing Why May Lead to Resolution",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 4,
    name: "Management Essentials: Controlling Bad Debt.",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 6,
    name: "A Meaningful Benefit: Employee Discounts",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 7,
    name: "By the Books: Employee Discount How-Tos",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 8,
    name: "Inquiries & Answers: Getting Employees to Work on Weekends",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 8,
    name: "Inquiries & Answers: Sacred Business",
  },
  {
    date: "June 2019",
    fileCore: "floral-finance-june-2019",
    page: 8,
    name: "Norms: Newspaper Print Ad Decline",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 2,
    name: "From the Publishers: Determination",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 2,
    name: "Why Customers Don't Pay: Knowing Why May Lead to Resolution",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 4,
    name: "Sign Language: Reap the Returns of Brand Recognition",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 6,
    name: "Outstanding Customer Service: Strategic Plans",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 7,
    name: "By the Books: Myths About Debt",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 8,
    name: "Inquiries & Answers: Ensuring the Best Product",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 8,
    name: "Inquiries & Answers: Too Many Sales",
  },
  {
    date: "May 2019",
    fileCore: "floral-finance-may-2019",
    page: 8,
    name: "Norms: Smartphone Users",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 2,
    name: "From the Publishers: Burnout",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 2,
    name: "Management Essentials: Building Your Customer Base: A Planned Approach Page 2",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 4,
    name: "Management Essentials: Cash Control & Sales Analysis.",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 6,
    name: "The Importance of a Good Accountant: Advice From a Seasoned Professional",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 7,
    name: "Percentages: What's So Important?",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 8,
    name: "Inquiries & Answers: Advertising",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 8,
    name: "Inquiries & Answers: Real Estate",
  },
  {
    date: "April 2019",
    fileCore: "floral-finance-april-2019",
    page: 8,
    name: "Norms: Smartphone Usage",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 2,
    name: "From the Publishers: Are You Having Fun?",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 2,
    name: "2019 Shop Profile: Doing It Right",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 4,
    name: "Management Essentials: Pricing",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 6,
    name: "Family Business Relationships: A Blessing and/or a Challenge?",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 7,
    name: "By the Books: Buying for Profit",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 8,
    name: "Inquiries & Answers: Skimming",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 8,
    name: "Inquiries & Answers: Advertising Woes",
  },
  {
    date: "March 2019",
    fileCore: "floral-finance-march-2019",
    page: 8,
    name: "Norms: Delivery Charge Minimum",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 2,
    name: "From the Publishers: Success & Significance.",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 2,
    name: "Getting the Best Lease: What You Need to Know to Negotiate Smart",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 4,
    name: "Management Essentials: Controlling Payroll",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 6,
    name: "Life Insurance: The Best Gift for Your Kids (or Grandkids)",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 7,
    name: "By the Books: Bank Reconciliation",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 8,
    name: "Inquiries & Answers: Contributions.",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 8,
    name: "Inquiries & Answers: Pricing Multiple Deliveries",
  },
  {
    date: "February 2019",
    fileCore: "floral-finance-february-2019",
    page: 8,
    name: "Norms: Mileage Rate",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 2,
    name: "From the Publishers: Introducing Management Essentials",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 2,
    name: "Management Essentials: Controlling Cost of Goods Sold: Part 1",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 4,
    name: "Management Essentials: Controlling Cost of Goods Sold: Part 2",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 6,
    name: "Perks: Something for Nothing?",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 7,
    name: "By the Books: Pricing Arrangements",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 8,
    name: "Inquiries & Answers: Monitoring Shrink",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 8,
    name: "Inquiries & Answers: Maintaining Profitability",
  },
  {
    date: "January 2019",
    fileCore: "floral-finance-january-2019",
    page: 8,
    name: "Norms: Three Big Expenses",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 2,
    name: "From the Publishers: Benefits of Anger?",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 2,
    name: "Business Plans Part 1: Defining Your Business and Where You Want to Take It",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 4,
    name: "Business Plans Part 2: The Numbers",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 5,
    name: "Business Plans Part 3:",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 6,
    name: "Business Plans Part 4: Marketing",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 7,
    name: "By the Books: Accounting for Replacements",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 8,
    name: "Inquiries & Answers: Designer Productivity,",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 8,
    name: "Inquiries & Answers: Extra URLs",
  },
  {
    date: "December 2018",
    fileCore: "floral-finance-december-2018",
    page: 8,
    name: "Norms: Non-Floral December Business",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 2,
    name: "From the Publishers: Getting People to Listen",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 2,
    name: "Inventory Management Part 1: Physical Inventory",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 4,
    name: "Inventory Management Part 2: Proper Inventory Accounting",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 6,
    name: "Leadership for Financial Success: An Imperative Skill Set",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 7,
    name: "By the Books: Direct Orders: Pros & Cons",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 8,
    name: "Inquiries & Answers: Delivery Zones",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 8,
    name: "Inquiries & Answers: Leaving Flowers",
  },
  {
    date: "November 2018",
    fileCore: "floral-finance-november-2018",
    page: 8,
    name: "Norms: Employees",
  },
];
